export const CORP_ADMIN_ROLES = ['ROLE_CORP_MASTER_ADMIN', 'ROLE_CORP_SUB_ADMIN'];
export const CORP_ROLES = [...CORP_ADMIN_ROLES, 'ROLE_CORP_USER'];
export const TA_ADMIN_ROLES = ['ROLE_TA_MASTER_ADMIN', 'ROLE_TA_SUB_ADMIN'];
export const TA_ROLES = [...TA_ADMIN_ROLES, 'ROLE_TA_USER'];
export const AEME_ADMIN_ROLES = ['ROLE_AEME_INTERNAL_ADMIN'];
export const ALL_ADMINS = [...CORP_ADMIN_ROLES, ...TA_ADMIN_ROLES, ...AEME_ADMIN_ROLES];
